name: Spellcheck

on:
  push:
  pull_request:

concurrency:
  group: spellcheck-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install typos
        uses: taiki-e/install-action@fe9759bf4432218c779595708e80a1aadc85cedc # v2.46.10
        with:
          tool: typos

      - name: Spell check
        run: typos --config=./.config/typos.toml
