name: Trigger Extension Update - Search

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version of Valkey Search module that was released
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: determine-vars
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Triggered by a release event."
            VERSION=${{ github.event.release.tag_name }}
          else
            echo "Triggered manually."
            VERSION=${{ inputs.version }}
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate token
        id: generate-token
        if: github.repository_owner == 'valkey-io'
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.VALKEYRIE_BOT_APP_ID }}
          private-key: ${{ secrets.VALKEYRIE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: valkey-bundle
          permission-contents: write

      - name: Trigger extension update
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ github.repository_owner == 'valkey-io' && steps.generate-token.outputs.token || secrets.EXTENSION_PAT }}
          repository: ${{ github.repository_owner }}/valkey-bundle
          event-type: search-release
          client-payload: >
            {
              "version": "${{ steps.determine-vars.outputs.version }}",
              "component": "search"
            }
